<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 footer-section desktop_version_footer">

                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <h4>Product</h4>
                    <ul>
                        <li><a href="#">Download app</a></li>
                        <li><a href="#">Features</a></li>
                        <li><a href="#">Support</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <h4>Company</h4>
                    <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Press</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <h4>Legal</h4>
                    <ul>
                        <li><a href="#" data-toggle="modal" data-target="#termsModal">Terms of Service</a></li>
                        <li><a href="#" data-toggle="modal" data-target="#privacyModal">Privacy Policy</a></li>
                    </ul>
                </div>
<div class="modal fade" id="termsModal" tabindex="-1" role="dialog" aria-labelledby="termsModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="termsModal" style="padding-left: 15px;padding-top: 10px;">Terms & Conditions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
<p>
        PLEASE READ THESE TERMS AND CONDITIONS OF USE CAREFULLY. THESE TERMS AND CONDITIONS OF USE MAY HAVE CHANGED SINCE YOUR LAST VISIT TO THIS WEBSITE AND TO THE PRODUCTS. YOU AGREE TO CHECK FOR UPDATES TO THESE TERMS AND CONDITIONS OF USE. BY USING THIS WEBSITE OR THE PRODUCTS, YOU INDICATE YOUR ACCEPTANCE OF THESE TERMS AND CONDITIONS OF USE. IF YOU DO NOT ACCEPT THESE TERMS AND CONDITIONS OF USE, THEN YOU MAY NOT USE THIS WEBSITE OR THE PRODUCTS.
Last revised March 2017

1. General Terms and Conditions.
1.1. General.
SKS Solutions LLC. DBA Crityk ("Crityk," "we" or "us") provides small businesses and organizations with a variety of products and services and related offerings, features and functionalities (individually, a "Product" and collectively, the "Products"). This website (including any related sub-site, service, feature or functionality) (the "Site") and the Products are provided subject to these Website and Product Terms and Conditions of Use, as they may be amended by us, and any guidelines, rules or operating policies that we may post on this website, including our Anti-Spam Policy, our Prohibited Content and Commerce Statement and our Privacy Statement, which are specifically incorporated herein by reference (collectively, the "Agreement"). We may amend this Agreement from time to time due to changes to the Site or the Products, to account for developments under the law, or for any other commercially reasonable reason. Future performance by us of our obligations under this Agreement is sufficient consideration for any such amendment. Any amendment will only become effective upon notification to you (by email or by posting on our Site) and, if you do not want to agree to any such amendment, you should stop using the Site and the Products and contact us to cancel your account. By checking the box or clicking the button next to a link to these terms on any of our sign-up pages, by logging in to your Crityk account, by accessing the Site or by accessing any of the Products (including by means of any API interface), you accept this Agreement on behalf of yourself and any business or organization you represent (collectively, "you"). Any terms and conditions that may be contained in any acknowledgement, invoice, purchase order or other form you provide are specifically null and void.
1.2. Minimum Age and Ability to Bind.
The Site and the Products are available only to persons or organizations that can form legally binding contracts under applicable law. Without limiting the foregoing, the Site and the Products are not available to individuals under the age of 18. If you do not qualify, you are not permitted to use the Site or the Products. If you are using the Site or the Products on behalf of an organization, you represent and warrant that you have the ability to bind such organization by your use of the Site and the Products.
1.3. Registration.
You agree to provide true, accurate, current and complete information about yourself and your organization, as applicable, as requested in the registration form and elsewhere on the Site, and agree to update such information if it changes.
1.4. Account Access.
We may, in our discretion, permit you to authorize additional users to use your Crityk account. For purposes of this Agreement, you are the "Account Owner" and any other users you authorize will be deemed "Authorized Users." You will be responsible for each Authorized User’s use of your Crityk account and each Authorized User’s compliance with this Agreement.

2. Communication with You.
We reserve the right to send messages to you to inform you of (a) changes or additions to the Site, the Products, this Agreement or the Fee Schedule (defined below), (b) violations of this Agreement or actions relating to your privilege to access and use the Site or the Products, (c) any other matter related to the Site, the Products or this Agreement or (d) for marketing and other purposes. Nothing in this provision shall require or obligate us to send any notice if no notice is required or mandated elsewhere in this Agreement. You may unsubscribe from our marketing communications at any time, although you will continue to receive transactional messages from us.
You agree that we may, but are not obligated to, monitor or record any of your telephone conversations and chat texts with us for quality control purposes, for purposes of training our employees and for our own protection. You further agree that any Account Users or anyone else you authorize to use your account consents to such monitoring or recording as well. You acknowledge that not all telephone lines or calls are recorded by us and that we do not guarantee that recordings of any particular telephone calls will be retained or are capable of being retrieved.
BY ENTERING INTO THIS AGREEMENT, YOU ACKNOWLEDGE THAT WE MAY CONTACT YOU VIA TELEPHONE (EITHER BY A LIVE PERSON, AUTOMATIC DIALER, PRERECORDED MESSAGE OR A COMBINATION OF THE FOREGOING) TO DISCUSS THE PRODUCTS AND YOU CONSENT TO SUCH CONTACT. FURTHER, YOU CONSENT TO RECEIVE SUCH PHONE CALLS AT THE TELEPHONE NUMBER YOU ENTERED ON THE SITE. You do not need to agree to this provision in order to use the Site or purchase the Products and if you would like us not to contact you by telephone, please send an email to support@crityk.com. Upon request, we may also contact you via telephone (including by automatic dialer or prerecorded message) or text you in order to provide you with your password or other information you request.

3. Copyright and Trademark Information.
The Site and the information it contains, are the property of Crityk and, in some cases, its affiliates and licensors, and are protected by United States and international intellectual property laws. "Crityk," the Crityk logo, "Safe Subscribe," "SafeUnsubscribe," and "Knowhow" are registered trademarks or trademarks of Crityk in the United States and other countries. This is not intended as a complete list of our trademarks and other Crityk product or service names or logos appearing in the Site may be trademarks of Crityk or its affiliates.

4. Fees; Payment; Taxes.
4.1. Fees.
(a) Fee Schedule. Once you have completed any applicable free trial period or exceeded any limits described on the applicable fee schedule (the "Fee Schedule"), you will be subject to fees in accordance with any applicable Fee Schedule. Applicable fees will be billed monthly or your pre-paid account will be debited monthly for the Products, even if you are not actively using the Products. The applicable Fee Schedule is subject to change at any time in our sole discretion, and if you do not agree to any such changes, you should contact us to cancel your account. We will use good faith efforts to notify you prior to the effectiveness of any significant change to the applicable Fee Schedule, but you are responsible for reviewing the applicable Fee Schedule from time to time and remaining aware of the fees charged by us and any applicable discounts. You acknowledge and agree that our measurements are the definitive measurements for payment due and owed hereunder.
(b) Other Billing Arrangements. If you receive the Products by means of one of our re-sellers or partners (a "Reseller"), the Reseller may be responsible for billing you for the Products and you may be subject to a different fee schedule and additional terms and conditions. You are responsible for reviewing your fee schedule and any additional terms and conditions. In the event of any conflict between this Agreement and the Reseller’s terms and conditions, this Agreement shall control except with respect to the payment provisions set forth in this Section 4. If you cease to be a customer of a Reseller, any special pricing, benefits or terms may no longer be available to you. We may rely on information provided by the Reseller, if any, with respect to the status of your Crityk account.
(c) Disputes. Notwithstanding anything set forth herein to the contrary, any disputes about any charges to you under this Agreement must be submitted to us in writing within 60 days of the date such charges are incurred. You agree to waive all disputes not brought within the 60 day period, and all such charges will be final and not subject to challenge.
4.2. Payment; Taxes.
(a) Payment. Payment for the Products will be made in advance by a payment method accepted by us. Checks (including e-checks or those sent by mail) will be accepted for prepayments of at least six months. Fees are only payable in the currencies made available to you when you purchase our Products. If the monthly payment option is selected or if you have previously provided us with your credit card or other payment method for payment, you hereby authorize us to charge by that payment method for such amounts on a regular monthly basis beginning at the end of any applicable free trial period and continuing until such time as your Crityk account is terminated. If we are for any reason unable to effect automatic payment, we will attempt to notify you by email and your Crityk account may be disabled until payment is received or we may, in our discretion, place your account in “suspend” status and charge you based on the then-current suspend fee schedule.
(b) Taxes. We collect and remit sales tax from our customers located in certain state and local jurisdictions, including those jurisdictions where software delivered as a service is taxable and where we maintain a physical presence. We determine your local taxing jurisdiction based on the billing address that you list in the "My Account" section of your Crityk account. Fees set forth in the applicable Fee Schedule do not take into account any taxes.
You agree to be responsible for and to pay any sales, personal property, use, VAT, excise, withholding, or any other taxes that may be imposed, based on this Agreement, use or possession of the Site or the Products or your products or services (except for taxes based on net income payable by us).

5. Access and Use of the Site and the Products.
5.1. Prohibition on Spam; Permission Practices; Message Requirements.
(a) Prohibition on Spam; Permission Practices. The Site and the Products may not be used for the sending of unsolicited email messages (sometimes called "spam"). All messages sent by means of the Site or the Products shall be in compliance with our Anti-Spam Policy.
You are responsible for ensuring that your use of the Site and the Products do not generate a number of spam or other complaints in excess of industry norms. We may terminate your access to or use of the Site and the Products if we determine that your level of spam or other complaints is higher than industry norms, as determined by us in our sole discretion. As a matter of privacy, we will not share with you information about those recipients who complain about your use of the Products or file a spam report against you.
You agree to import, access or otherwise use only contact lists in connection with the Site and the Products for which all listed parties have consented to receive correspondence from you (such as by opting into your "Join My Mailing List" link). It is not sufficient consent to receive email correspondence from you if a person or organization participates in a survey or registers for an event, clicks "Like" on your Facebook® page, or "follows" you on Twitter®. If you have used our feature that allows you to request a recipient to confirm that you have the recipient's permission to send messages to such recipient (assuming such use is permitted by laws applicable to you), and such recipient has not responded or does not respond affirmatively to such request for confirmation, you agree that you shall not send messages to that recipient. You agree not to send messages through the Site or the Products to distribution lists, newsgroups, publicly available press or media addresses or purchased email addresses.
We reserve the right without notice to take all measures of any nature (whether legal, technical or otherwise) to prevent unsolicited bulk email and/or other unauthorized email, messages or campaigns from entering, utilizing or remaining within our network.
(b) Messages. In your use of the Site or the Products, you shall represent yourself or your organization accurately and will not impersonate any other person, whether actual or fictitious.
You agree that you are the sole or designated "sender" (as such term is defined in the CAN-SPAM Act of 2003 and any rules or regulations adopted under such act (the "CAN-SPAM Act")) of any message sent by you using the Site or the Products. Similarly, for messages sent to Canadian email accounts, you are the sole person sending or causing or permitting the message to be sent by you using the Site or the Products (within the meaning of Canada's Anti-Spam Legislation, S.C. 2010, c. 23 ("Canada's Anti-Spam Legislation")).
You agree that for any email message sent by you using the Site or the Products, (i) the "from" line of any email message sent by you using the Site or the Products will accurately and in a non-deceptive manner identify your organization, your product or your service, (ii) the "subject" line of any email message sent by you using the Site or the Products will not contain any deceptive or misleading content regarding the overall subject matter of the email message, and (iii) you will include your valid physical address, which, if you are located in the United States, may be a valid post office box meeting the registration requirements established by the United States Postal Service.
(c) Unsubscribe. Every email message sent in connection with the Products must contain an "unsubscribe" link that allows subscribers to remove themselves from your mailing list and a link to the then-current About Our Service Provider description. Each such link must remain operational for at least 60 days after the date on which you send the message, and must be in form and substance satisfactory to us. You agree that you will not remove, disable or attempt to remove or disable either link. You shall monitor and process unsubscribe requests received by you directly within 10 days of submission and update the email addresses to which messages are sent through your Crityk account. You cannot charge a fee, require the recipient to give you any personally identifying information beyond an email address, or make the recipient take any step other than sending a reply email or visiting a single page on an Internet website as a condition for honoring an unsubscribe request. As required under the CAN-SPAM Act and other applicable laws, you acknowledge that you are responsible for maintaining and honoring the list of unsubscribe requests following termination of your Crityk account and this Agreement.
You agree that you shall not utilize the Site or the Products to send any message the primary purpose of which is the commercial advertisement or promotion of a commercial product or service (including content on an Internet website operated for a commercial purpose) (a "commercial electronic mail message" as defined in the CAN-SPAM Act or Canada's Anti-Spam Legislation) to any person who has opted out or otherwise objected to receiving such messages from you or another sender on whose behalf you may be acting.
5.2. Compliance with Laws.

The Site and the Products shall only be used for lawful purposes and you shall use the Site and the Products only in compliance with this Agreement and all other applicable U.S., state, local and international laws in your jurisdiction, including:

the CAN-SPAM Act;
Canada's Anti-Spam Legislation;
any policies and laws related to unsolicited emails, spamming, privacy, obscenity, or defamation, copyright and trademark infringement and child protective email address registry laws;
laws relating to advertising, sales or promotional efforts or practices, redemption, refunds and provision of your products or services;
laws that govern false, unfair and deceptive practices, coupons, gift cards/certificates, defective products or services, unclaimed property, alcohol or tobacco, health and safety, fire, and hygiene standards;
laws that govern lotteries, sweepstakes, contests and promotions; and
laws that govern the collection of donations and charitable giving.
You further agree to refrain from unethical, false or misleading advertising, promotions or sales efforts and practices in connection with your use of our Site or Products.
You may not use our Site or Products for any unlawful or discriminatory activities, including acts prohibited by the Federal Trade Commission Act, Fair Credit Reporting Act, Equal Credit Opportunity Act, or other laws that apply to commerce.
You are responsible for determining whether our Site or Products are suitable for you to use in light of any regulations, such as the Health Insurance Portability and Accountability Act ("HIPAA"), the Gramm-Leach-Blilely Act, European data privacy laws, or other laws. If you are subject to a particular regulation and you use our Site or Products, then we will not be liable if our Site or Products do not meet those requirements.
5.3. Restrictions on Use.
We prohibit the use of the Site or the Products by any person or organization that violates our Prohibited Content and Commerce Statement.You further agree to comply with the following in connection with your use of the Site and the Products:
You may not access or use the Site or the Products in a way that uses technology or other means to access, index, re-render, frame, mirror, truncate, add to, inject, filter or link to the Site or the Products that is not authorized by us (including by removing, disabling, bypassing, or circumventing any content protection or access control mechanisms intended to prevent the unauthorized use, download, linking, framing, reproduction, access to, or distribution of the Site or the Products).
You shall not use the Site, the Products or any Software for timesharing or service-bureau purposes or otherwise for the benefit of a third party (except as expressly permitted by our partner programs).
Unless you are an authorized reseller of the Products, you may not display, copy, reproduce, or distribute the Software, any component thereof, any documentation provided in connection with Site, the Products or the Software, or any content, including but not limited to newsletters distributed to you by us in connection with the Products.
You may not use any deep-link, page-scrape, robot, crawl, index, spider, offline reader, click spam, macro programs, internet agent, or other automatic device, program, algorithm or methodology which does the same things, to use, access, copy, index, acquire information, generate impressions or clicks, input information, store information, search, generate searches, or monitor any portion of the Site or the Products for any unauthorized purpose.
You may not use the Site or the Products in a way that, to be determined in our sole discretion, damages, disables, overburdens, impairs, or gains unauthorized access to the Site or the Products, including Crityk’s servers, computer network, or user accounts.
You may not use the Site or the Products in a way that removes, modifies, disables, blocks, obscures or otherwise impairs any advertising in connection with the Site or the Products.
You may not copy, display, distribute, download, license, modify, publish, re-post, reproduce, reuse, sell, transmit, use to create a derivative work, or otherwise use the content of the Site or the Products for public or commercial purposes without our express written permission.
You shall not interfere with or disrupt the Site or any related Crityk websites or servers or networks connected to the Site or the Products.
You shall not restrict or inhibit any other user from enjoying and using the Site or the Products.
You shall not use the Site or the Products in violation of applicable law or third party rights (including third party terms of service), and shall not use the Site or the Products for hosting content (for example, images and documents) that infringes on the intellectual property rights of others.
You shall not repeatedly upload and remove unique email addresses or otherwise try to manipulate data in an attempt to circumvent our Fee Schedule or other billing procedures.
You shall not set up multiple accounts for any individual or organization in order to send substantially similar content unless you are part of a franchise.
You may only use our templates, any images we provide, or any other features or functionality of the Products with the Products themselves (for example, you may not take an image or template and use it on your website). This restriction also applies to customized templates prepared by our professional services group.
You shall not use documents and images hosted by us on servers controlled by us for any purpose whatsoever other than in connection with the Products. If you own the document or image, you can use it outside of the Products so long as it is not hosted by us.
You shall not include any incentives (for example, coupons, discounts or awards) in any messages you send by means of the Site or the Products that encourage a recipient to forward the message to another recipient, other than as expressly encouraged and permitted within the applicable Product.
5.4. Limitations on Use.
You understand that not all messages or campaigns sent through use of the Site or the Products will be received by or will be capable of being viewed by their intended recipients or will be viewable by your recipients in the same way they appear in our product environment. You further understand that delivery of messages by means of the Site or the Products may involve transmissions over various networks, and that the messages (including images and text contained therein) could be reformatted or otherwise revised to conform to the formatting or technical requirements of such networks. You also understand and agree that messages exceeding maximum character limitations may be truncated, abbreviated, reduced or otherwise abruptly cut short.
You agree that we may establish general practices and limits concerning use of the Site or the Products, including the maximum number of messages or campaigns that may be distributed by you and/or the maximum size of any messages or campaigns that may be transmitted by means of the Site or the Products. We reserve the right to modify, revise, suspend or discontinue any Product in whole or in part, either temporarily or permanently and with or without notice, and you acknowledge that we are not obligated to support or update the Products in any manner. If we discontinue any Product in its entirety that you are using, we will provide you with advance notice and an opportunity to cancel your account.
5.5. Subscriber Privacy.
(a) Customer Privacy Notice. You shall adopt and comply with your own “customer privacy policy.” You privacy policy will be posted so that your subscribers have notice of your data collection and use practices, including your practices with respect to subscriber data that you obtain from us, and will otherwise comply with applicable law. We have provided you with information regarding our use of subscriber data in the About Our Service Provider link, which may be modified by us from time to time. Your customer privacy policy will either adopt the About Our Service Provider link or include substantially similar disclosure (and update such disclosure from time to time) so that your subscribers are aware of how their data is used by you and us.
(b) Sensitive Information. You will not import or incorporate into any contact lists or other content you upload to our servers any of the following information: social security numbers, national insurance numbers, credit cards, passwords, security credentials, or sensitive personal or health information of any kind. Notwithstanding the foregoing, if you are a covered entity under HIPAA, you agree to contact us at legal@crityk.com in order to request a business associate agreement prior to using the Product with your subscribers. If we agree to enter into a business associate agreement with you, you may include sensitive personal health information, subject to this Agreement and the terms of the business associate agreement (additional fees may apply).
5.6. Your Products and Services.
Among other things, the Products permit you to (i) communicate about or administer contests, competitions, sweepstakes, or other similar promotional events ("Promotions"); (ii) sell your products and services and tickets to your events to your subscribers and others in the form of various promotional deals, coupons, tickets, vouchers, passes or cards (each, a "Deal"); and (iv) collect donations (each, a "Donation Campaign").
You are solely responsible for your products and services, events, Promotions, Deals and Donation Campaigns, including any and all injuries, illnesses, damages, claims, liabilities and costs suffered in respect thereto. You shall bear all costs of procuring and delivering your products and services, Promotions (including any prizes offered), Deals, running your events and Donation Campaigns, including any associated shipping, taxes and any other fees associated therewith. You hold all necessary governmental and third party licenses, approvals, authorizations and registrations necessary to offer your products and services, Promotions, Deals and run your events and Donation Campaigns, if any.
You agree to provide your products and services, Promotions, Deals, and run your events and Donation Campaigns in a safe and professional manner, consistent with industry best practices, including keeping reliable records.
You will be solely responsible for any and all statements and promises you make and for all user assistance, warranty and support of your products and services, Promotions, Deals, events and Donation Campaigns and to comply with any promises you make to your customers, users, donors and donees. You further agree to provide contact information for any end-user questions, complaints or claims. You agree that your Promotions and Deals will prominently include any applicable rules, restrictions or limitations necessary to comply with applicable law, this Agreement and your own requirements (the "Offer Terms") and you agree to comply with the same. Any such Offer Terms must be presented to prospective purchasers before they commit to make a payment or take any other action and must include any terms provided by us. If you use the Site or the Products to offer a Promotion, you are further responsible for ensuring that you comply with applicable law relating to eligibility requirements (for example, age and residency restrictions), the selection of winners and all prizes offered in connection with the Promotion (for example, registration and obtaining necessary regulatory approvals) and that your Offer Terms include the foregoing to the extent applicable. You shall ensure that the rules for each Promotion (i) state that each entrant or participant unconditionally releases us of any liability arising from the Promotion, and (ii) inform each entrant or participant that the Promotion is in no way sponsored, endorsed or administered by, or associated with, us.
If you use the Site or the Products to offer a deal, ticket, coupon, voucher, pass or card in connection with Apple Inc. ("Apple") products ("Passes"), you shall not charge any fees to end-users in order to access your Passes (although you may charge them to purchase your Passes) and you acknowledge that such Passes are distributed by Crityk under the Crityk trademark or brand.
5.7. Listing Service.
(a) Storefront Service. If you use the Products to manage, display, update and/or distribute Storefronts, photos or other images, text, PDFs, trademarks, names, logos and any other applicable content (the "Business Content") on and to our network of third party local and national websites, mobile applications, and any of our mobile sites and/or websites (the "Network"), you will be subject to the additional terms and conditions below. "Storefronts" shall mean a compilation of products, services and/or menu items, pricing, descriptions, dietary information and other similar items.
You will provide all Business Content in PDF, Microsoft Word, spreadsheet, email or any other reasonable format requested by us.
You will administer and update your Business Content on a regular basis, but in no event less frequently than you do offline.
You grant us an irrevocable, non-exclusive, royalty-free, perpetual, transferrable, worldwide license, with the right to sublicense, to use, reproduce, create derivative works from, modify, reformat, update, publish, edit, translate, distribute, perform and display such Business Content on and to our Network and to use the Business Content as described in our Privacy Statement.
You hereby designate us as your agent (i) to create any social media, digital marketing or any other accounts requested by you (orally or in writing) (each an "Account") that may be used with the Products (e.g. Twitter or Facebook), (ii) to act on your behalf to add to or update your Business Content on any third party websites (including logging in to such sites on your behalf and "claiming" any account, listing or profile for you or sending an email or postcard to such sites), and (iii) to agree to any applicable terms of service or other contract on your behalf in accordance with the foregoing. You further ratify any express or implied grant of agency previously given to us (whether oral or in writing) and any actions we took on your behalf prior to the execution of this Agreement relating to the foregoing. You agree to promptly change any passwords provided to you by us with respect to any Accounts.
(b) Website Integration Service. In our sole discretion, we may make available certain code (the "Website Code") to enable you to integrate the Storefront into your website and/or to enable you to redirect your website to our mobile site for your business or, upon your request, we may implement the Website Code for you. You represent and warrant that if you request that we implement the Website Code for you and you share your website credentials with us, that you have the right to do the same. We hereby grant you a nonexclusive, revocable license to use the Website Code solely in the format provided to you. We may revoke this license at any time by providing you with written notice of such revocation. This license will automatically terminate upon the end of the Term.
5.8. Footers.
For every listing, message or campaign sent or distributed via the Products, you agree that we may add a link to our Site and a statement such as "Email Marketing by Crityk" or "Powered by Crityk" in the footer or other similar location that does not unreasonably obscure the message or campaign.

6. Communities and Marketplace.
The Site may contain areas where you may be able to publicly post information or communicate with others (for example, discussion boards or blogs), review products and merchants and otherwise submit content, including the Crityk Community and the Crityk Marketplace (the "Communities"). You agree that you are responsible for your own use of such Communities, for any posts you make and for any consequences thereof. You agree that we are not responsible for the content of any postings in any Community and have no duty to monitor such Communities or to correct any erroneous statements set forth therein. Any information you post may be accessible to anyone with Internet access, and any personal or other information you include in your posting may be read, collected and used by others.
You agree that you will use any such Community in compliance with all applicable laws and this Agreement. You further agree to abide by the Crityk Community Terms and Conditions of Use with respect to your use of the Crityk Community and the Crityk Marketplace Terms and Conditions of Use with respect to your use of the Crityk Marketplace. In the event that you violate any provision of the Crityk Community Terms and Conditions of Use or the Crityk Marketplace Terms and Conditions of Use, in our sole discretion, we reserve the right to terminate your access to or use of the Site or the Products, disable your Crityk account or access to the Site or the Products, and remove all or a portion of your content, in each case, with or without cause, with or without notice and without refund.
We reserve the right, but shall have no obligation, to investigate your use of any community for any reason, including in order to (a) determine whether a violation of this Agreement has occurred, or (b) comply with any applicable law, legal process or governmental request. We have no obligation to maintain or continue operation of any Community, and we may cease operation of, or modify, all or any portion of any such Community at any time in our sole discretion and without notice to you.
Many of the products and services being promoted by means of the Communities are offered by and are the sole responsibility of the person or entity that made such postings. We do not endorse and are not responsible for (i) any third party products or services marketed or made available through the Communities, or (ii) any purchase or other transaction resulting from or associated with your use of the Communities.

7. Restrictions and Responsibilities.
7.1. No Rights in Software.
This is an Agreement for services and access to the Site, and, except as expressly set forth herein, you are not granted a license to any software by this Agreement and nothing on the Site shall be construed to confer any grant or license of any intellectual property rights, whether by estoppel, by implication, or otherwise. You will not, directly or indirectly, reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, or algorithms of, or found at or through the Site or the Products or any software, documentation, or data related to the Site or the Products ("Software"); remove any proprietary notices or labels from the Site or the Products or any Software; modify, translate, or create derivative works based on the Site or the Products or any Software; or copy, distribute, pledge, assign, or otherwise transfer or encumber rights to the Site or the Products or any Software. If you are using the Site or the Products in any jurisdiction which restricts the ability of a software provider to restrict your right to reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, or algorithms of the Site, the Software or the Products, then you hereby covenant that, prior to engaging in such activities, you will first request that we perform such work at our standard professional services rates. We can then decide either: (a) to perform the work in order to achieve such interoperability and charge our then standard rates for such work to you; (b) to permit you to reverse engineer parts of the Software in order to obtain such source code, but only to the extent necessary to achieve such interoperability; or (c) to provide you with the information that you need regarding the Software for the purpose for which applicable law permits you to engage in such activities despite a contractual prohibition on such activities.
7.2. Monitoring and Removal.
Although we have no obligation to monitor the content provided by you or your use of the Site or the Products, we may do so and may block any messages or campaigns, remove any content, including surveys, event registrations, social campaigns, Promotions, Deals or Business Content, or prohibit any use of the Site or the Products that we believe may be in violation of the foregoing or any other provision of this Agreement. You further understand and agree that we and any applicable third party who supports, posts, publishes or distributes your Promotions, Deals or Business Content also has the right to reformat, edit, monitor, reject, block or remove any of your Promotions, Deals or Business Content at any time. In no case will the foregoing make us responsible or liable for compliance with any such laws or obligations, for which you remain solely responsible and liable.
7.3. Assistance.
You acknowledge that we may from time to time provide you with marketing advice and other coaching, template design, frequently asked questions and tips on best practices and complying with applicable law, including any sample Offer Terms. You acknowledge that such assistance and information is provided as a convenience to you and that such assistance and information are not intended to and do not constitute legal advice and that no attorney-client relationship is formed. We do not warrant or guarantee that use of or compliance with this information will be sufficient to comply with your obligations hereunder, applicable law or with third party rights.
7.4. Your Information and Content.
(a) Your Information. In using the varied features of the Site or the Products, you may provide information about yourself or your employer (such as name, contact information, or other registration information) to us and we may collect information about your use of the Site or the Products. We may use this information in accordance with our Privacy Statement and relevant "just-in-time" notices, if any, provided at the point of information collection or use.
(b) Your Content and Contacts. We will also obtain any information that you provide to us in connection with your use of the Site or the Products, such as contact lists (including email addresses and phone numbers of your subscribers) and content (including Business Content). We acknowledge your ownership rights in such contact lists. As more fully described in our Privacy Statement, we will never sell or rent your contact lists to anyone without your permission.
You hereby grant to us a revocable, non-exclusive, royalty-free, worldwide license, with the right to sublicense, to use, reproduce, publish, distribute, perform and display your contacts and content (other than the Business Content, which is covered by the license set forth in Section 5.7 hereof) only as required by us to offer and operate the Products and related services and as described in our Privacy Statement. If you use any of the features in the Products whereby you offer Passes, you agree that Apple may use (i) screen shots of your Passes; (ii) trademarks and logos associated with your Passes; and (iii) any text, descriptions, representations or information relating to Passes made available to end-users on or in connection with your Passes, in each case for promotional purposes in marketing materials and gift cards. You also permit Apple to use images and other materials that Apple requests for promotional purposes in marketing materials and gift cards.
You are solely responsible for the accuracy, quality, integrity, legality, reliability and appropriateness of your contacts and content, and you are responsible for maintaining, securing and storing your contacts and content in accordance with applicable law and any contractual obligations you may have (including this Agreement). You represent and warrant that you own or have secured all rights and interest in and to your contacts and content required for us to use your contacts and content as contemplated by this Agreement. To the extent, you use images or templates provided by us, we hereby grant to you a revocable, non-exclusive, royalty-free, worldwide license to use, reproduce, publish, distribute, perform and display the images solely in connection with your use of the Site or the Products.
(c) Submissions. If you submit any suggestions, business information, ideas, concepts or inventions or content to us through the Site or otherwise ("Submissions"), you agree such Submission is non-confidential for all purposes and you automatically grant, or warrant that the owner of such content or intellectual property has expressly granted, us a non-exclusive, royalty-free, perpetual, irrevocable, worldwide license, with the right to sublicense, to use, reproduce, create derivative works from, modify, publish, edit, translate, distribute, perform and display such Submission in any manner or in any media now known or hereafter created.
(d) Automated Data Collection. You consent to us collecting data from your website through automated means, such as through harvesting bots, robots, spiders, or scrapers ("Automated Data Collection") and the use of that data for internal business purposes. We will not use Automated Data Collection to collect data from your website if you have set the /robots.txt file to disallow such collection.
(e) Backups. You are responsible for making frequent backup copies of your contacts and content.

8. Termination.
You may terminate your Crityk account at any time by emailing Crityk Customer Support. Except as specifically set forth herein or on the Site, there are no refunds for any fees paid. YOU ARE SOLELY RESPONSIBLE FOR TERMINATING YOUR CRITYK ACCOUNT AND THIS AGREEMENT. WE ARE NOT RESPONSIBLE FOR YOUR FAILURE TO PROPERLY TERMINATE YOUR CRITYK ACCOUNT AND THIS AGREEMENT OR FOR ANY CREDIT CARD OR OTHER CHARGES OR FEES YOU INCUR AS A RESULT OF YOUR FAILURE TO PROPERLY TERMINATE YOUR CRITYK ACCOUNT AND THIS AGREEMENT.
We may, in our sole discretion, terminate your Crityk account or your access to or use of the Site or the Products, disable your Crityk account or access to the Site or the Products, remove all or a portion of your contacts and content, cancel or suspend any of your events, Promotions or Deals or Donation Campaigns, or put your Crityk account on inactive status, in each case at any time, with or without cause, with or without notice and without refund. We shall have no liability to you or any third party because of such termination or action, except that we will refund a pro rata portion of any prepaid amounts if we terminate you without cause. After termination, you shall process all unsubscribe requests within 30 days of your last email campaign. Upon request within 30 days of your termination, we will provide the list of unsubscribe requests from your Crityk account to you. Under the CAN-SPAM Act and Canada's Anti-Spam Legislation, you acknowledge that you are responsible for maintaining and honoring the list of unsubscribe requests following termination of your Crityk account and this Agreement.
If your Crityk account is classified (at our sole discretion) as inactive for over 120 days, we have the right to permanently delete any of your contacts and content.
Upon termination of your Crityk account by you or us, this Agreement and any rights or licenses granted to you hereunder, shall immediately terminate except that (a) all sections of this Agreement that by their nature should survive termination will survive termination, including, Sections 1- 3, 4.1(c), 4.2 and 5-18, and (b) for the avoidance of doubt, you will continue to be responsible for redemption of coupons and fulfillment for Promotions and Deals run prior to such termination in accordance herewith and any promises you made with respect to the funds associated with any Donation Campaigns.

9. Indemnification.
You hereby agree to defend, indemnify and hold harmless us, our affiliates and our underlying service providers (i.e. vendors who help us provide the Products), business partners, third-party suppliers and providers, members of our Network, account providers, licensors, distributors and agents and our and their respective officers, directors, employees, distributors and agents from and against any claims, damages, suits, actions, demands, proceedings (whether legal or administrative), losses, liabilities, penalties, settlements and expenses (including costs and reasonable attorneys' fees) in connection with any claim or action that (a) arises from any actual or alleged breach by you of this Agreement; (b) arises from your contacts and content, including the content or effects of any messages you distribute, events you host, surveys you administer, social media campaigns you publish, Promotions or Deals you offer, donations you collect or products or services you sell (including claims relating to violations of law, false advertising, injuries, illness, damages, death, taxes, fulfillment, breach of Offer Terms, defective products or services or unclaimed property); (c) arises from your provision of incomplete or inaccurate information to your subscribers or customers; (d) arises from your activities or postings in any Community; (e) arises from your use of any Third Party Service (as defined below); (f) arises from your activities related to the Crityk Authorized Local Expert Program or the Crityk Boot Camp; or (g) otherwise arises from or relates to your use of the Site or the Products. You agree to provide us with prompt written notice in the event of any such claims or actions. In addition, you acknowledge and agree that we have the right to seek damages when you use the Site or the Products for unlawful purposes, in an unlawful manner, or in a manner inconsistent with the terms of this Agreement, and that such damages may include, without limitation, direct, indirect, special, incidental, cover, reliance and/or consequential damages. In the event that we are required to respond to a third party or law enforcement subpoena or court order that is related to your use of the Site or the Products, we may, in our sole discretion, require you to reimburse us for our reasonable expenses associated with complying with such subpoena or order.

10. Warranty Disclaimer; Remedies; Release.
YOU EXPRESSLY AGREE THAT THE SITE AND THE PRODUCTS (INCLUDING ANY CUSTOM SERVICES OFFERINGS) ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. USE OF THE SITE OR THE PRODUCTS AND ANY RELIANCE BY YOU UPON THE SITE OR THE PRODUCTS, INCLUDING ANY ACTION TAKEN BY YOU BECAUSE OF SUCH USE OR RELIANCE, IS AT YOUR SOLE RISK. WE DO NOT WARRANT THAT THE USE OF THE SITE OR THE PRODUCTS WILL BE UNINTERRUPTED OR ERROR FREE OR COMPLETELY SECURE, NOR DO WE MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SAME. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. NO STATEMENT OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM US IN ANY MEANS OR FASHION SHALL CREATE ANY WARRANTY NOT EXPRESSLY AND EXPLICITLY SET FORTH IN THIS AGREEMENT.
WE SHALL HAVE NO LIABILITY OF ANY NATURE WHATSOEVER FOR YOUR COMPLIANCE WITH OR BREACH OF ANY LICENSE OR TERMS AND CONDITIONS OF ANY THIRD PARTIES OR THIRD PARTY SERVICES.
IN ADDITION, WE DO NOT ENDORSE AND ARE NOT RESPONSIBLE FOR (a) THE ACCURACY OR RELIABILITY OF ANY THIRD-PARTY CONTENT, OPINION, ADVICE OR STATEMENT MADE BY ANYONE OTHER THAN US, OR (b) ANY EVENT HOSTED, DONATION SOLICITED, THE RESULTS OF ANY SURVEY, OR ANY PRODUCT OR SERVICE PURCHASED OR OTHERWISE OBTAINED FROM ANY THIRD PARTY, INCLUDING OUR CUSTOMERS.
NO CLAIM MAY BE ASSERTED BY YOU AGAINST US MORE THAN 12 MONTHS AFTER THE DATE OF THE CAUSE OF ACTION UNDERLYING SUCH CLAIM. YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY FAILURE OR NONPERFORMANCE OF THE SITE OR THE PRODUCTS SHALL BE FOR US TO USE COMMERCIALLY REASONABLE EFFORTS TO ADJUST OR REPAIR THE SITE OR THE PRODUCTS.
TO THE EXTENT APPLICABLE LAW PERMITS, YOU RELEASE US FROM ANY CLAIMS OR LIABILITY RELATED TO (a) ANY CONTENT POSTED ON YOUR SITE OR IN ANY MATERIALS YOU SEND USING THE SITE OR THE PRODUCTS, (b) THE CONDUCT OF ANY OTHER CUSTOMERS OF OURS OR THEIR RESPECTIVE SUBSCRIBERS AND (c) ANY PROBLEMS THAT MAY ARISE FROM ANY REMOTE ACCESS TO YOUR COMPUTERS OR OTHER SYSTEMS YOU PROVIDE TO OUR PERSONNEL OR AGENTS FOR THE PURPOSE OF TROUBLESHOOTING ISSUES. YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 (IF YOU ARE A CALIFORNIA RESIDENT), AND ANY SIMILAR PROVISION IN ANY OTHER JURISDICTION (IF YOU ARE A RESIDENT OF SUCH JURISDICTION).

11. Limitation of Liability.
EXCEPT WITH RESPECT TO DEATH OR PERSONAL INJURY DUE TO THE NEGLIGENCE OF CRITYK, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, TORT, CONTRACT, OR OTHERWISE, SHALL CRITYK OR ANY OF ITS UNDERLYING SERVICE PROVIDERS, BUSINESS PARTNERS, THIRD PARTY SUPPLIERS AND PROVIDERS AND MEMBERS OF OUR NETWORK, ACCOUNT PROVIDERS, LICENSORS, OFFICERS, DIRECTORS, EMPLOYEES, DISTRIBUTORS OR AGENTS (COLLECTIVELY REFERRED TO FOR PURPOSES OF THIS SECTION AS "CRITYK") BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY MONEY DAMAGES, WHETHER DIRECT, INDIRECT, SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES, EVEN IF CRITYK SHALL HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY, AND REGARDLESS OF THE FORM OF ACTION (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE), THE MAXIMUM AGGREGATE LIABILITY OF CRITYK TO YOU ARISING IN CONNECTION WITH THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT YOU PAID FOR THE APPLICABLE PRODUCT IN THE 12 MONTHS PRIOR TO THE ACCRUAL OF THE APPLICABLE CLAIM, LESS ANY DAMAGES PREVIOUSLY PAID BY CRITYK TO YOU IN THAT 12 MONTH PERIOD. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT APPLY TO YOU.
You agree that Crityk has set its prices and entered into this Agreement in reliance upon the disclaimers of warranty and the limitations of liability set forth herein, that they reflect an allocation of risk between the parties (including the risk that a contract remedy may fail of its essential purpose and cause consequential loss), and that they form an essential basis of the bargain between the parties.

12. Restricted Persons; Export of the Site, the Products or Technical Data.
You hereby represent and warrant that you are not a Restricted Person. For purposes of this Agreement, you are a "Restricted Person" if you or any officer, director, or controlling shareholder of the entity on behalf of which you are using the Site or the Products is (a) a national of or an entity existing under the laws of any country with which U.S. persons are prohibited from engaging in transactions, as may be determined from time to time by the U.S. Treasury Department; (b) designated as a Specially Designated National or institution of primary money laundering concern by the U.S. Treasury Department; (c) listed on the Denied Persons List or Entity List by the U.S. Commerce Department; (d) engaged in nuclear, missile, chemical or biological weapons activities to which U.S. persons may not contribute without a U.S. Government license; or (e) owned, controlled, or acting on behalf of a Restricted Person. If you become a Restricted Person during the term of this Agreement, you shall notify us within 24 hours, and we shall have the right to terminate any further obligations to you, effective immediately and with no further liability to you; provided, however, for the avoidance of doubt, you will remain liable to us for any outstanding obligations hereunder. You agree that you shall not utilize the Site or the Products to conduct or facilitate any transaction with any Restricted Person, except as may be expressly authorized in advance in writing by the U.S. Government. You may not remove or export from the United States or allow the export or re-export of the Site or the Products, or any direct product thereof, including technical data, in violation of any restrictions, laws, or regulations of the United States or any other applicable country.

13. Third-Party Websites and Services.
The Site and the Products include social media tools that may, among other things, allow you to manage access, post content and manage content on social network platforms (for example, LinkedIn®, Facebook and Twitter). These tools also allow you to use the Products to access and analyze information found on social media sites. You hereby grant us all required permissions to access such sites and provide this functionality.
The Site may contain links to websites that are controlled by third parties and access to certain third-party services (including our partners), which may include, without limitation, marketing and advertising services, social bookmarking services, social network platforms, publication and delivery services, payment processing services and other payment intermediaries or websites and members of our Network (each, a "Third Party Service"). These links and services are provided to you as a convenience, and we are not affiliated with or responsible for the content, action or performance of any linked website or Third-Party Service and you use such websites or services at your own risk. Any Third-Party Service accessed from the Site or the Products is independent from us and we have no control over, and assume no responsibility for, the content, privacy policy, terms of use and practices of such website or service. Any such Third-Party Service may have terms of use and a privacy policy different than ours and you should review the applicable terms and policies, including privacy and data gathering practices before proceeding.
You agree to abide by the terms and conditions of any applicable Third Party Service (including Facebook, Paypal and Apple). Notwithstanding anything set forth herein to the contrary, you will abide by this Agreement regardless of anything to the contrary in your agreement with any third party and you shall not use such Third-Party Service to avoid the restrictions set forth in this Agreement.
We may terminate any Third-Party Service's ability to interact with the Site or any of the Products at any time, with or without notice, and in our sole discretion, with no liability to you or to any third party. Any Third-Party Service may take actions to impact our ability to make available some or all of the features of the Site or the Products at any time, with or without notice, and we will not be liable to you or to any third party for any such actions. We accept no responsibility for reviewing changes or updates to, or the quality, content, policies, nature or reliability of, any Third-Party Services.
In order to use some features of the Site or the Products, you must have access to a valid email or social networking account. You are solely responsible for paying any third-party fees associated with such third-party networks. You further agree that the ability to use some features of the Site or the Products may be subject to subscriber terms of use, contracts, capacity charges and/or other expenses established and enforced by your email service provider, internet service provider or other applicable service provider, all of which are your sole responsibility. You represent that use of the Product will not violate any rules, restrictions policies, or requirements of your email service provider, internet service provider or other applicable service provider.
In no event shall any reference to any third party or third party product or Third Party Service be construed as an approval or endorsement by us of that third party or of any product or service provided by such third party.
If you use the Products to collect payments (including registration for events, Deals, Digital Rewards, donations or products or services), you are responsible for the collection and administration of such payments and compliance with all applicable laws relating thereto, including all applicable domestic or international local, state or federal tax requirements. We do not hold your funds or those of your subscribers, customers, participants, event registrants or donors at any time. You are responsible for any refunds associated with any payments.

14. Notice and Take Down Procedures; Copyright Agent.
If you believe any materials accessible on or from the Site or the Products infringe your copyright or other intellectual property, you may request removal of those materials (or access thereto) from the Site or the Products by contacting our copyright agent (identified below) and providing the following information:
Identification of the copyrighted work that you believe to be infringed. Please describe the work, and where possible include a copy or the location (for example, the URL) of an authorized version of the work.
Identification of the material that you believe to be infringing and its location. Please describe the material, and provide us with its URL or any other pertinent information that will allow us to locate the material.
Any information required to be included in a copyright infringement report under the United Kingdom Digital Economy Act 2010 (as we shall notify to you from time to time and request from you as necessary).
Your name, address, telephone number and (if available) email address.
A statement that you have a good faith belief that the complained of use of the materials is not authorized by the copyright owner, its agent, or the law.
A statement that the information that you have supplied is accurate, and indicating that "under penalty of perjury," you are the copyright owner or are authorized to act on the copyright owner's behalf.
A signature or the electronic equivalent from the copyright holder or authorized representative.
Our agent for copyright issues relating to the Site and the Products is as follows:
Compliance Manager
SKS Solutions LLC. 
1222 McClellan Dr. Apt. 3
Los Angeles, CA 90025
Phone: (310) 9803227
Email: info@crityk.com
For all email submissions please include the subject line: DMCA Takedown Request.
In an effort to protect the rights of copyright owners, we maintain a policy for the termination, in appropriate circumstances, of Crityk account holders who are repeat infringers.

15. Open Positions on Career Pages.
We may list open employment positions on the Site. Any such postings are for informational purposes only and are subject to change without notice. You should not construe any information on the Site or made available through the Site as an offer for employment, nor should you construe anything on the Site as a promotion or solicitation for employment not authorized by the laws and regulations of your location.

16. Username and Password.
You are responsible for maintaining the security of your Crityk account, passwords and files (including the passwords and files that your Authorized Users, if any, have access to) and any Accounts. We will accept the instructions of any individual who claims to be authorized to direct changes to your Crityk account so long as such person presents the Account Owner username and password or provides other appropriate account identifying information, as determined by us in our sole discretion, by email or by phone, or through a Third Party Service, if any, through which you access the Site or the Products. We have no knowledge of your organizational structure, if you are registering for the Products as an organization, or your personal relationships, if you are a person. You will be solely responsible and liable for any activity that occurs under your username and the activities of your Authorized Users, if any, and we shall not be responsible for the actions of any individuals who misuse or misappropriate your contact lists or other assets using your username and password or other appropriate account identifying information. You agree to notify us immediately of any unauthorized use of your Crityk account or any other breach of security.

17. International Use; Prohibited by Law.
In recognition of the global nature of the Internet, you agree to comply with all local rules where you reside or your organization is located regarding online activities, email and the Site or the Products. More specifically, but without limitation, you agree to comply with all applicable laws regarding the transmission of technical data exported to or from the United States or the country in which you reside. The Site or the Products are controlled and operated by us from our offices within the United States (although we may share data with third parties around the world to assist us in providing the Site or the Products) and we make no representation that the Site or the Products are appropriate or available for use in other locations. Those who access the Site or the Products from other locations do so at their own initiative and risk, and are fully responsible for compliance with all applicable laws in those locations. We do not offer the Site or the Products where prohibited by law.
For the purposes of European Directive 95/46/EC and applicable national implementing laws in your jurisdiction, and with respect to your subscribers’ or customers’ personal data, you acknowledge and agree that you are the data controller, and we are a data processor. You also acknowledge and agree that you are responsible for complying with all obligations of a data controller under applicable law. We agree that we shall process your subscribers’ or customers’ personal data on your behalf in accordance with your instructions, as set out in this Agreement and in order to provide the Products, and any instructions received from time to time, and that we have taken and will continue to take adequate technical and organizational measures against unauthorized or unlawful processing of, accidental loss or destruction of, or damage to, your subscribers' or customers' personal data as set out in our Privacy Statement.
If you are located in the European Economic Area (“EEA”) or send to anyone in the EEA, you represent and warrant that in using our Services, you will clearly describe in writing how you plan to use any data collected and you will get express consent to transfer data to us and be processed and that you have the necessary permission to allow us to receive and process data and send communications to that individual on your behalf. If, notwithstanding the foregoing, you still require a model clauses contract with us, please contact us at legal@crityk.com to request one.

18. Miscellaneous.
18.1. Full Force and Effect.
If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.
18.2. Entire Agreement.
We and you agree that this Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed by both parties, except as otherwise provided herein. No delay or omission by either party in exercising any right or remedy under this Agreement or existing at law or equity shall be considered a waiver of such right or remedy.
18.3. Assignment.
You may not assign any of your rights hereunder. We may assign all rights to any other individual or entity in our sole discretion.
18.4. Further Assurances.
You agree to execute any and all documents and take any other actions reasonably required to effectuate the purposes of this Agreement.
18.5. Force Majeure.
We are not liable for any default or delay in the performance of any of our obligations under this Agreement if such default or delay is caused, directly or indirectly, by forces beyond our reasonable control, including fire, flood, acts of God, labor disputes, accidents, acts of war or terrorism, interruptions of transportation or communications, supply shortages or the failure of any third party to perform any commitment relative to the production or delivery of any equipment or material required for us to perform our obligations hereunder.
18.6. Third Party Beneficiaries.
Crityk’s affiliates, underlying service providers, business partners, third-party suppliers and providers, members of our Network, account providers, licensors, officers, directors, employees, distributors and agents are expressly made third party beneficiaries of this Agreement. Except as set forth in the immediately preceding sentence, nothing express or implied in this Agreement is intended to confer, nor shall anything herein confer, upon any person other than the parties and the respective permitted successors or assigns of the parties, any rights, remedies, obligations or liabilities whatsoever.
18.7. Titles.
The titles of the paragraphs of this Agreement are for convenience only and have no legal or contractual effect.
18.8. No Agency.
Except as expressly set forth herein, no agency, partnership, joint venture, or employment is created as a result of this Agreement, and you do not have any authority of any kind to bind us in any respect whatsoever.
18.9. Attorney Fees.
In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover its costs and attorneys' fees.
18.10. Governing Law and Legal Actions.
If you signed up to use the Site or the Products prior to June 7, 2016, the following terms shall apply:
This Agreement shall be governed by and construed in accordance with the laws of the Republic of California. All legal actions in connection with the Agreement shall be brought in the state or federal courts located in Los Angeles, California.
If you signed up to use the Site or the Products on or after June 7, 2016, the following terms shall apply:
You hereby submit to the exclusive jurisdiction of the American Arbitration Association (“AAA”) in connection with any dispute relating to, concerning or arising out of this Agreement, whether in contract, tort, fraud, misrepresentation or any other legal theory. The arbitration will be conducted before a single arbitrator and will be held at the AAA location in Boston, Massachusetts, unless you are a “consumer” as defined under the AAA rules. Disputes with consumers, as therein defined, will be resolved by binding arbitration conducted under the AAA’s Consumer Arbitration Rules, as applicable. Consumers may request that the arbitration occur in or near the city/state stated in your account record with us. The procedures for commencing an arbitration are available here (provided however, that you may assert claims in small claims court, if your claims qualify and so long as the matter remains in such court only on an individual, non-class basis).
ARBITRATION MUST BE ON AN INDIVIDUAL BASIS. THIS MEANS NEITHER YOU NOR WE MAY JOIN OR CONSOLIDATE CLAIMS IN ARBITRATION BY OR AGAINST OTHER SUBSCRIBERS OR USERS, OR LITIGATE IN COURT OR ARBITRATE ANY CLAIMS AS A REPRESENTATIVE OR MEMBER OF A CLASS OR IN A PRIVATE ATTORNEY GENERAL CAPACITY.
Only a court, and not an arbitrator, shall determine the validity and effect of the class action waiver. Even if all parties have opted to litigate a claim in court, you or we may elect arbitration with respect to any claim made by a new party or any new claims later asserted in that lawsuit.
Payment of all filing, administration and arbitrator fees will be governed by the AAA’s rules, unless otherwise stated in this paragraph. In the event you are able to demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, we will pay as much of your filing, administrative, and arbitrator fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive.
No arbitration award or decision will have any preclusive effect as to issues or claims in any dispute with anyone who is not a named party to the arbitration. If you initiate a litigation or any other proceeding against us in violation of this paragraph, you agree to pay our reasonable costs and attorneys’ fees incurred in connection with its enforcement of this paragraph.
The parties shall maintain the confidential nature of the arbitration proceeding and any award, including the hearing, except as may be necessary to prepare for or conduct the arbitration hearing on the merits, or except as may be necessary in connection with a court application for a preliminary remedy, a judicial challenge to an award or its enforcement, or unless otherwise required by law or judicial decision.
This Agreement and the rights of the parties hereunder shall be governed by and construed in accordance with the laws of the Commonwealth of Massachusetts, exclusive of conflict or choice of law rules.
The parties acknowledge that this Agreement evidences a transaction involving interstate commerce. Notwithstanding the provision in the preceding paragraph with respect to applicable substantive law, any arbitration conducted pursuant to the terms of this Agreement shall be governed by the Federal Arbitration Act (9 U.S.C., Secs. 1-16).
18.11. Additional Information.
If you have any questions about the rights and restrictions above, or would like to report any inaccuracies or errors, please contact us by email at legal@crityk.com.

19. UK Site Visitors and Customers.
If you are accessing the Site or purchasing any Products from the UK, Sections 9, 10 and 11 of this Agreement will not apply to you as set out above, but will be replaced in their entirety with the following wording:
"9. Indemnification.
You hereby agree to defend, indemnify and hold harmless us, our affiliates and our underlying service providers, (i.e. vendors who help us provide the Products) or suppliers business partners, members of our Network, account providers, licensors, distributors and agents and us and their respective officers, directors, employees, distributors and agents from and against any claims, damages, suits, actions, demands, proceedings (whether legal or administrative) losses, liabilities, penalties, settlements and expenses (including costs and reasonable legal fees) in connection with any claim or action that (a) arises from a breach by you of any of the following Sections of this Agreement: 1, 2, 4-8, or 18; (b) arises from a breach by you of the Anti-Spam Policy or Privacy Statement or of your obligations as a data controller under applicable law; (c) arises from your contacts and content, including the content or effects of any messages you distribute, events you host, surveys you administer, social media campaigns you publish, Promotions or Deals you offer, donations you collect or products or services you sell (including, claims relating to violations of law, false advertising, injuries, illness, damages, death, taxes, fulfillment, breach of Offer Terms, defective products or services or unclaimed property); (d) arises from your provision of incomplete or inaccurate information to your subscribers or customers; (e) arises from your activities or postings in any Community in breach of the terms of this Agreement; (f) arises from your use of any Third Party Service (as defined below), in breach of the terms of this Agreement or the terms of any agreement in place with the relevant Third Party Service; or (g) arises from your activities related to the Crityk Authorized Local Expert Program or the Crityk Boot Camp in breach of the terms of this Agreement.
10. Warranty Disclaimer; Remedies; Release.
YOU EXPRESSLY AGREE THAT THE SITE AND THE PRODUCTS (INCLUDING ANY CUSTOM SERVICES OFFERINGS) ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. USE OF THE SITE OR THE PRODUCTS AND ANY RELIANCE BY YOU UPON THE SITE OR THE PRODUCTS, INCLUDING ANY ACTION TAKEN BY YOU BECAUSE OF SUCH USE OR RELIANCE, IS AT YOUR SOLE RISK. WE DO NOT WARRANT THAT THE USE OF THE SITE OR THE PRODUCTS WILL BE UNINTERRUPTED OR ERROR FREE OR COMPLETELY SECURE, NOR DO WE MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SAME. TO THE EXTENT PERMITTED BY APPLICABLE LAW, WE EXPRESSLY EXCLUDE ALL CONDITIONS, WARRANTIES AND OTHER TERMS WHICH MIGHT OTHERWISE BE IMPLIED BY STATUTE, COMMON LAW OR THE LAW OF EQUITY. NO STATEMENT OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM US IN ANY MEANS OR FASHION SHALL CREATE ANY WARRANTY NOT EXPRESSLY AND EXPLICITLY SET FORTH IN THIS AGREEMENT.
WE SHALL HAVE NO LIABILITY OF ANY NATURE WHATSOEVER FOR YOUR COMPLIANCE WITH OR BREACH OF ANY LICENSE OR TERMS AND CONDITIONS OF ANY THIRD PARTIES OR THIRD PARTY SERVICES.
IN ADDITION, WE DO NOT ENDORSE AND ARE NOT RESPONSIBLE FOR (a) THE ACCURACY OR RELIABILITY OF ANY THIRD PARTY CONTENT, OPINION, ADVICE OR STATEMENT MADE BY ANYONE OTHER THAN US, OR (b) ANY EVENT HOSTED, DONATION SOLICITED, DONATION SOLICITED, THE RESULTS OF ANY SURVEY, OR ANY PRODUCT OR SERVICE PURCHASED OR OTHERWISE OBTAINED FROM ANY THIRD PARTY, INCLUDING OUR CUSTOMERS.
TO THE EXTENT APPLICABLE LAW PERMITS, YOU RELEASE US FROM ANY CLAIMS OR LIABILITY RELATED TO (a) ANY CONTENT POSTED ON YOUR SITE OR IN ANY MATERIALS YOU SEND USING THE SITE OR THE PRODUCTS, (b) FROM ANY CLAIMS RELATED TO THE CONDUCT OF ANY OTHER CUSTOMERS OF OURS OR THEIR RESPECTIVE SUBSCRIBERS, AND (c) ANY PROBLEMS THAT MAY ARISE FROM ANY REMOTE ACCESS TO YOUR COMPUTERS OR OTHER SYSTEMS YOU PROVIDE TO OUR PERSONNEL OR AGENTS FOR THE PURPOSE OF TROUBLESHOOTING ISSUES.
11. Limitation of Liability.
EXCEPT WITH RESPECT TO FRAUDULENT MISREPRESENTATION, DEATH OR PERSONAL INJURY DUE TO THE NEGLIGENCE OF CRITYK, OR LIABILITY THAT MAY NOT OTHERWISE BE LIMITED OR EXCLUDED BY LAW, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, TORT (INCLUDING NEGLIGENCE), CONTRACT, BREACH OF STATUTORY DUTY OR OTHERWISE, SHALL CRITYK OR ANY OF ITS UNDERLYING SERVICE PROVIDERS, BUSINESS PARTNERS,MEMBERS OF OUR NETWORK, INFORMATION PROVIDERS, ACCOUNT PROVIDERS, LICENSORS, OFFICERS, DIRECTORS, EMPLOYEES, DISTRIBUTORS OR AGENTS (COLLECTIVELY REFERRED TO FOR PURPOSES OF THIS SECTION AS "CRITYK") BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY LOSS OF PROFITS, REVENUE, BUSINESS, GOODWILL OR ANTICIPATED SAVINGS, OR FOR ANY INDIRECT OR CONSEQUENTIAL LOSSES, EVEN IF FORESEEABLE OR IF CRITYK SHALL HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY, OTHER THAN WHERE CAUSED BY CRITYK'S MATERIAL BREACH OF THIS AGREEMENT, AND REGARDLESS OF THE FORM OF ACTION (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), BREACH OF STATUTORY DUTY, PRODUCT LIABILITY OR OTHERWISE), THE MAXIMUM AGGREGATE LIABILITY OF CRITYK TO YOU ARISING IN CONNECTION WITH THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT YOU PAID FOR THE APPLICABLE PRODUCT IN THE 12 MONTHS PRIOR TO THE ACCRUAL OF THE APPLICABLE CLAIM, LESS ANY DAMAGES PREVIOUSLY PAID BY CRITYK TO YOU IN THAT 12 MONTH PERIOD.
You agree that Crityk has set its prices and entered into this Agreement in reliance upon the disclaimers of warranty and the limitations of liability set forth herein, that they reflect an allocation of risk between the parties (including the risk that a contract remedy may fail of its essential purpose and cause consequential loss), and that they form an essential basis of the bargain between the parties."</p>

      </div>
      
    </div>
  </div>
</div>

<div class="modal fade" id="privacyModal" tabindex="-1" role="dialog" aria-labelledby="privacyModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="privacyModal" style="padding-left: 15px;padding-top: 10px;">Privacy & Policy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
<p>
This Privacy Policy is effective as of September 28, 2016.
Our Privacy Policy explains how we collect, use, share and protect information in relation to our mobile services, web site, and any software provided on or in connection with using the Crityk website or Crityk application services (collectively, the “Service“), and your choices about the collection and use of your information.
By using our Service you understand and agree that we are providing a platform for you to post content, including photos, comments and other materials (“User Content“), to the Service and to share User Content publicly. This means that other Users may search for, see, use, or share any of your User Content that you make publicly available through the Service, consistent with the terms and conditions of this Privacy Policy and our Terms of Use (which can be found here www.Critykapp.com/terms).
This Privacy Policy applies to all visitors, users, and others who access the Service (“Users“).
What information do we collect?
Information you submit directly:
Your username, password and e-mail address when you register for a Crityk account.
Profile information that you provide for your user profile (e.g., first and last name, profile picture, bio description, username, and phone number). This information allows us to help you or others be “found” on Crityk.
Information from social media accounts you connect (e.g. email address, profile pictures, usernames, and credentials)
User Content (e.g., photos, comments, ratings, location, and other materials) that you post to the Service.
Communications between you and SKS Solutions or Crityk. For example, we may send you Service-related emails (e.g., account verification, changes/updates to features of the Service, technical and security notices). You may not opt out of Service-related e-mails.
Locating and Inviting your friends on Crityk:
If you choose to find or invite your friends through your device’s contacts list, then Crityk will access your contacts list to determine whether or not someone associated with your contact is using Crityk.
If you choose to find or invite your friends through a third-party social media site, then you will be prompted to set up a link to the third-party service and you understand that any information that such service may provide to us will be governed by this Privacy Policy.
If you choose to find your friends through a search of names or usernames on Crityk then simply type a name to search and we will perform a search on our Service.
Note about “Invite Friends” feature:If you choose to invite someone to the Service through our “Invite friends” feature, you may select a person directly from the contacts list on your device and send a text or email from your personal account. You understand and agree that you are responsible for any charges that apply to communications sent from your device, and because this invitation is coming directly from your personal account, Crityk does not have access to or control this communication.
Analytics information:
We use third-party analytics tools to help us measure traffic and usage trends for the Service. These tools collect information sent by your device or our Service, including the web pages you visit, add-ons, and other information that assists us in improving the Service.
Cookies and similar technologies:
When you visit the Service, we may use cookies and similar technologies like pixels, web beacons, and local storage to collect information about how you use Crityk and provide features to you.
Device identifiers:
When you use a mobile device like a tablet or phone to access our Service, we may access, collect, monitor, store on your device, and/or remotely store one or more “device identifiers.” Device identifiers are small data files or similar data structures stored on or associated with your mobile device, which uniquely identify your mobile device. A device identifier may be data stored in connection with the device hardware, data stored in connection with the device’s operating system or other software, or data sent to the device by Crityk.
A device identifier may deliver information to us or to a third party partner about how you browse and use the Service and may help others or us provide reports or personalized content in the future. Information collected through device identifiers may include device locations, including specific geographic locations, such as through GPS, Bluetooth, or WiFi signals utilized on your device. Some features of the Service may not function properly if use or availability of device identifiers is impaired or disabled.
Metadata:
Metadata is usually technical data that is associated with User Content. For example, Metadata can describe how, when and by whom a piece of User Content was collected and how that content is formatted.
Users can add or may have Metadata added to their User Content including a hashtag (e.g., to mark keywords when you post a photo or comment), geotag (e.g., to mark your location to a photo), comments or other data. This makes your User Content more searchable by others and more interactive.
How do we use your information?
In addition to some of the specific uses we outline in this Privacy Policy, we may use information that we receive to do the following:
fulfill customer support requests
help you efficiently access your information after you sign in
remember information so you will not have to re-enter it during your visit or the next time you visit the Service;
provide personalized content and information to you and others, this may be based on your location and/or preferences provided to us during your usage
provide, improve, test, and monitor the effectiveness of our Service
develop and test new products and features
monitor metrics such as total number of visitors, traffic, and demographic patterns
provide feedback to businesses listed on the Service
diagnose or fix technology problems
automatically update the Crityk application on your device
comply with legal obligations
enhance the security of the Service
Please remember that the information you post to the Service is intended for public consumption, including your reviews, photos, comments, likes, friends, lists, and account profile. We may display this information on the Service, share it with businesses, and further distribute it to a wider audience through third party sites and services.
How and with whom do we share your information? 
We will not rent or sell your information to third parties outside SKS Solutions without your consent, except as noted in this Policy.
We may share User Content and your information (including but not limited to, information from cookies, log files, device identifiers, location data, and usage data) with businesses that are legally part of the same group of companies that SKS Solutions is part of, or that become part of that group (“Affiliates”). Affiliates may use this information to help provide, understand, and improve the Service (including by providing analytics) and Affiliates’ own services (including by providing you with better and more relevant experiences).
We also may share your information as well as information from tools like cookies, log files, and device identifiers and location data, with third-party organizations that help us provide the Service to you (“Service Providers”). Our Service Providers will be given access to your information as is reasonably necessary to provide the Service under reasonable confidentiality terms.
We may remove parts of data that can identify you and share anonymous data with other parties. We may also combine your information with other information in a way that it is no longer associated with you and share that aggregated information.
Parties with whom you may choose to share your User Content:
Any information or content that you voluntarily disclose for posting to the Service, such as User Content, becomes available to the public. Once you have shared User Content or made it public, that User Content may be re-shared by others.
Any User Content that you make public is searchable by other Users and subject to re-use.
If you remove information that you posted to the Service, copies may remain viewable in cached and archived pages of the Service, or if other Users or third parties using Crityk have copied, shared, or saved that information.
What happens in the event of a change of control?
If we sell or otherwise transfer part or the whole of SKS Solutions or our assets to another organization (e.g., in the course of a transaction like a merger, acquisition, bankruptcy, dissolution, liquidation), your information such as name and email address, User Content and any other information collected through the Service may be among the items sold or transferred. You will continue to own your User Content. We will make commercially reasonable efforts to ensure the buyer or transferee will honor the commitments we have made in this Privacy Policy.
Responding to legal requests and preventing harm:
We may access, preserve and share your information in response to a legal request (like a search warrant, court order or subpoena) if we have a good faith belief that the law requires us to do so. This may include responding to legal requests from jurisdictions outside of the United States where we have a good faith belief that the response is required by law in that jurisdiction, affects users in that jurisdiction, and is consistent with internationally recognized standards. We may also access, preserve and share information when we have a good faith belief it is necessary to: detect, prevent and address fraud and other illegal activity; to protect ourselves, you and others, including as part of investigations; and to prevent death or imminent bodily harm. Information we receive about you may be accessed, processed and retained for an extended period of time when it is the subject of a legal request or obligation, governmental investigation, or investigations concerning possible violations of our terms or policies, or otherwise to prevent harm.
How do we store and protect your information?
Storage and Processing:
Your information collected through the Service may be stored and processed in the United States or any other country in which SKS Solutions or its Affiliates or Service Providers maintain facilities.
SKS Solutions, its Affiliates, or Service Providers may transfer information that we collect about you, including personal information across borders and from your country or jurisdiction to other countries or jurisdictions around the world. If you are located in the European Union or other regions with laws governing data collection and use that may differ from U.S. law, please note that we may transfer information, including personal information, to a country and jurisdiction that does not have the same data protection laws as your jurisdiction.
By registering for and using the Service you consent to the transfer of information to the U.S. or to any other country in which SKS Solutions, its Affiliates or Service Providers maintain facilities and the use and disclosure of information about you as described in this Privacy Policy.
We use commercially reasonable safeguards to help keep the information collected through the Service secure and take reasonable steps (such as requesting a unique password) to verify your identity before granting you access to your account. However, SKS Solutions cannot ensure the security of any information you transmit to Crityk or guarantee that information on the Service may not be accessed, disclosed, altered, or destroyed.
Your privacy settings may also be affected by changes the social media services you connect to Crityk make to their services. We are not responsible for the functionality, privacy, or security measures of any other organization.
What are your choices about the use of your information? 
Your account information and profile/privacy settings:
Update your account at any time by logging in and changing your profile settings.
Unsubscribe from email communications from us by clicking on the “unsubscribe link” provided in such communications. As noted above, you may not opt out of Service-related communications (e.g., account verification, purchase and billing confirmations and reminders, changes/updates to features of the Service, technical and security notices).
How long do we keep your User Content?
Following termination or deactivation of your account, SKS Solutions, Crityk, its Affiliates, or its Service Providers may retain information (including your profile information) and User Content for a commercially reasonable time for backup, archival, and/or audit purposes.
Security
We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet or via mobile device, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.
Children’s Privacy
SKS Solutions and Crityk do not knowingly collect or solicit any information from anyone under the age of 13 or knowingly allow such persons to register for the Service. The Service and its content are not directed at children under the age of 13. In the event that we learn that we have collected personal information from a child under age 13 without parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please contact us.
Other Web Sites and Services
We are not responsible for the practices employed by any websites or services linked to or from our Service, including the information or content contained within them. Please remember that when you use a link to go from our Service to another website or service, our Privacy Policy does not apply to those third-party websites or services. Your browsing and interaction on any third-party website or service, including those that have a link on our website, are subject to that third party’s own rules and policies. In addition, you agree that we are not responsible and do not have control over any third-parties that you authorize to access your User Content. If you are using a third-party website or service and you allow them to access your User Content you do so at your own risk.
Changes To This Privacy Policy
SKS Solutions may modify or update this Privacy Policy from time to time, so please review it periodically. We may provide you additional forms of notice of modifications or updates as appropriate under the circumstances. Your continued use of Crityk or the Service after any modification to this Privacy Policy will constitute your acceptance of such modification
Questions or Comments?
If you have any questions or concerns regarding your privacy while using the Service, please send a detailed message to: legal@crityk.com. We will make every effort to resolve your concerns.
</p>


  </div>
    </div>
  </div>
</div>



                <div class="col-lg-2 col-md-3 col-sm-12 col-xs-12">

                </div>

                <div class="col-lg-4 col-md-3 col-sm-12 col-xs-12">
                    <h4>Follow Us</h4>
                    <ul class="followus">
                        <li><a href="https://www.facebook.com/crityk/" target="_blank"><img src="{{ asset('vendor/crytik/') }}/images/fb-bottom.svg" alt=""></a></li>
                        <li><a href="https://www.instagram.com/crityk/" target="_blank"><img src="{{ asset('vendor/crytik/') }}/images/int.png" alt=""></a></li>
                        <li><a href="#"><img src="{{ asset('vendor/crytik/') }}/images/green-icon.svg" alt=""></a></li>
                        <li><a href="https://twitter.com/crityk1" target="_blank"><img src="{{ asset('vendor/crytik/') }}/images/tw-bottom.svg" alt=""></a></li>
                    </ul>
                </div>

            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 footer-section mobile_version_footer">

                <div class="col-sm-6 col-xs-6">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                        <h4>Product</h4>
                        <ul>
                            <li><a href="#">Download app</a></li>
                            <li><a href="#">Features</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>


                <div class="col-sm-6 col-xs-6">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                        <h4>Company</h4>
                        <ul>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Press</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                        <h4>Legal</h4>
                        <ul>
                            <li><a href="#">Terms of Service</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>


                    <div class="col-lg-2 col-md-3 col-sm-12 col-xs-12">

                    </div>


                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                    <ul class="followus">
                        <li><a href="https://www.facebook.com/crityk/" target="_blank"><img src="{{ asset('vendor/crytik/') }}/images/fb-bottom.svg" alt=""></a></li>
                        <li><a href="https://www.instagram.com/crityk/" target="_blank"><img src="{{ asset('vendor/crytik/') }}/images/int.png" alt=""></a></li>
                        <li><a href="#"><img src="{{ asset('vendor/crytik/') }}/images/green-icon.svg" alt=""></a></li>
                        <li><a href="https://twitter.com/crityk1" target="_blank"><img src="{{ asset('vendor/crytik/') }}/images/tw-bottom.svg" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid bottom-icon">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">
                <img src="{{ asset('vendor/crytik/') }}/images/bottom-icon.svg">
            </div>
        </div>
    </div>
    <div class="container-fluid coyright-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <p>© 2017 SKS Solutions LLC</p>
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-center">
                        <img src="{{ asset('vendor/crytik/') }}/images/logofooter.png">
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-right full_bottom_icon">
                        <img src="{{ asset('vendor/crytik/') }}/images/bottom-icon.svg" class="">
                    </div>

                    

                </div>
            </div>
        </div>
    </div>
</footer>


